name: new_mobilek
description: Ўзбекитон касаба уюшмалари федератсияси.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">= 2.11.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ">= 4.7.0"
  get: ^4.6.5
  get_storage: ^2.0.3
  path_provider: ^2.0.11
  http: ^0.13.0
  url_launcher: ^6.1.5
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Uzkuf/

flutter_icons:
  image_path: "assets/images/icon-50.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#1E489C"
